// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Pocogeneratortest
{

    // AdCampaigns
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public class AdCampaignConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<AdCampaign>
    {
        public AdCampaignConfiguration()
            : this("dbo")
        {
        }

        public AdCampaignConfiguration(string schema)
        {
            ToTable("AdCampaigns", schema);
            HasKey(x => x.AdCampaignId);

            Property(x => x.AdCampaignId).HasColumnName(@"AdCampaignID").HasColumnType("bigint").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.AdCampaignType).HasColumnName(@"AdCampaignType").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(100);
            Property(x => x.AdCampaignTemplate).HasColumnName(@"AdCampaignTemplate").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.AdGroupName).HasColumnName(@"AdGroupName").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(500);
            Property(x => x.DateCreated).HasColumnName(@"DateCreated").HasColumnType("date").IsOptional();
        }
    }

}
// </auto-generated>
