// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Pocogeneratortest
{

    // DealerExcludedModels
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public class DealerExcludedModelConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<DealerExcludedModel>
    {
        public DealerExcludedModelConfiguration()
            : this("dbo")
        {
        }

        public DealerExcludedModelConfiguration(string schema)
        {
            ToTable("DealerExcludedModels", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.DealerId).HasColumnName(@"DealerId").HasColumnType("int").IsRequired();
            Property(x => x.ModelName).HasColumnName(@"ModelName").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(500);
            Property(x => x.DateCreated).HasColumnName(@"DateCreated").HasColumnType("datetime").IsRequired();
        }
    }

}
// </auto-generated>
