// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Pocogeneratortest
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public class GetDealerMakeInformationReturnModel
    {
        public System.Int32? DealerId { get; set; }
        public System.String ClientName { get; set; }
        public System.Int32? DivisionId { get; set; }
        public System.Int32? ManufacturerId { get; set; }
        public System.String DivisionName { get; set; }
        public System.String FranchiseString { get; set; }
    }

}
// </auto-generated>
