// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Pocogeneratortest
{

    public partial interface IMyDbContext : System.IDisposable
    {
        System.Data.Entity.DbSet<AdCampaign> AdCampaigns { get; set; } // AdCampaigns
        System.Data.Entity.DbSet<AdCampaignSetting> AdCampaignSettings { get; set; } // AdCampaignSettings
        System.Data.Entity.DbSet<AdTemplate> AdTemplates { get; set; } // AdTemplates
        System.Data.Entity.DbSet<AquisioFeedExportLog> AquisioFeedExportLogs { get; set; } // AquisioFeedExportLogs
        System.Data.Entity.DbSet<Auditing> Auditings { get; set; } // Auditing
        System.Data.Entity.DbSet<DealerExcludedModel> DealerExcludedModels { get; set; } // DealerExcludedModels
        System.Data.Entity.DbSet<DealerGeoTown> DealerGeoTowns { get; set; } // DealerGeoTowns
        System.Data.Entity.DbSet<DealerNameOverride> DealerNameOverrides { get; set; } // DealerNameOverrides
        System.Data.Entity.DbSet<ExceptionLog> ExceptionLogs { get; set; } // ExceptionLog
        System.Data.Entity.DbSet<MakeOverride> MakeOverrides { get; set; } // MakeOverrides
        System.Data.Entity.DbSet<ModelOverride> ModelOverrides { get; set; } // ModelOverrides

        int SaveChanges();
        System.Threading.Tasks.Task<int> SaveChangesAsync();
        System.Threading.Tasks.Task<int> SaveChangesAsync(System.Threading.CancellationToken cancellationToken);
        System.Data.Entity.Infrastructure.DbChangeTracker ChangeTracker { get; }
        System.Data.Entity.Infrastructure.DbContextConfiguration Configuration { get; }
        System.Data.Entity.Database Database { get; }
        System.Data.Entity.Infrastructure.DbEntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class;
        System.Data.Entity.Infrastructure.DbEntityEntry Entry(object entity);
        System.Collections.Generic.IEnumerable<System.Data.Entity.Validation.DbEntityValidationResult> GetValidationErrors();
        System.Data.Entity.DbSet Set(System.Type entityType);
        System.Data.Entity.DbSet<TEntity> Set<TEntity>() where TEntity : class;
        string ToString();

        // Stored Procedures
        int GetAdCampaigns(int? pageNo, int? perPage, string sortColumn, string sortOrder);
        // GetAdCampaignsAsync cannot be created due to having out parameters, or is relying on the procedure result (int)

        int GetAdCampaignTemplates(int? pageNo, int? perPage, string sortColumn, string sortOrder);
        // GetAdCampaignTemplatesAsync cannot be created due to having out parameters, or is relying on the procedure result (int)

        int GetAdCampiagnGroups(int? pageNo, int? perPage, string sortColumn, string sortOrder);
        // GetAdCampiagnGroupsAsync cannot be created due to having out parameters, or is relying on the procedure result (int)

        System.Collections.Generic.List<GetAdTemplatesReturnModel> GetAdTemplates(int? adCampaignId, int? dealerId, int? pageNumber, int? perPage);
        System.Collections.Generic.List<GetAdTemplatesReturnModel> GetAdTemplates(int? adCampaignId, int? dealerId, int? pageNumber, int? perPage, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<GetAdTemplatesReturnModel>> GetAdTemplatesAsync(int? adCampaignId, int? dealerId, int? pageNumber, int? perPage);

        System.Collections.Generic.List<GetDealerMakeInformationReturnModel> GetDealerMakeInformation(int? dealerId);
        System.Collections.Generic.List<GetDealerMakeInformationReturnModel> GetDealerMakeInformation(int? dealerId, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<GetDealerMakeInformationReturnModel>> GetDealerMakeInformationAsync(int? dealerId);

        System.Collections.Generic.List<GetDealerMakeModelsReturnModel> GetDealerMakeModels(int? dealerId, string sortBy, string orderBy);
        System.Collections.Generic.List<GetDealerMakeModelsReturnModel> GetDealerMakeModels(int? dealerId, string sortBy, string orderBy, out int procResult);
        System.Threading.Tasks.Task<System.Collections.Generic.List<GetDealerMakeModelsReturnModel>> GetDealerMakeModelsAsync(int? dealerId, string sortBy, string orderBy);

        GetExportLogsReturnModel GetExportLogs(string sortColumn, string sortBy, int? pageNumber, int? pageSize);
        System.Threading.Tasks.Task<GetExportLogsReturnModel> GetExportLogsAsync(string sortColumn, string sortBy, int? pageNumber, int? pageSize);

        int GetMakeOverrides(int? pageNumber, int? perPage, string sortCoumn, string orderBy);
        // GetMakeOverridesAsync cannot be created due to having out parameters, or is relying on the procedure result (int)

        int GetModelOverrides(int? pageNumber, int? perPage, string sortCoumn, string orderBy);
        // GetModelOverridesAsync cannot be created due to having out parameters, or is relying on the procedure result (int)

        GetOffermanagerPaymentSettingsReturnModel GetOffermanagerPaymentSettings(int? accountId);
        System.Threading.Tasks.Task<GetOffermanagerPaymentSettingsReturnModel> GetOffermanagerPaymentSettingsAsync(int? accountId);

        GetVehicleOptionsReturnModel GetVehicleOptions(int? dealerId, int? year, string make);
        System.Threading.Tasks.Task<GetVehicleOptionsReturnModel> GetVehicleOptionsAsync(int? dealerId, int? year, string make);

        int GetVehiclePaymentsForAquisio(int? year, string make, string model, int? pageSize, int? pageNumber);
        // GetVehiclePaymentsForAquisioAsync cannot be created due to having out parameters, or is relying on the procedure result (int)

        int VcmsGetHomeNetVehivlesAquisioNew();
        // VcmsGetHomeNetVehivlesAquisioNewAsync cannot be created due to having out parameters, or is relying on the procedure result (int)

    }

}
// </auto-generated>
