// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Pocogeneratortest
{

    // MakeOverrides
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public class MakeOverride
    {
        public int Id { get; set; } // Id (Primary key)
        public string Make { get; set; } // Make (length: 50)
        public string NewMakeName { get; set; } // NewMakeName (length: 100)
        public System.DateTime DateCreated { get; set; } // DateCreated
        public System.DateTime? DateModified { get; set; } // DateModified
    }

}
// </auto-generated>
