// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Pocogeneratortest.Entities
{

    // AdCampaigns
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public class AdCampaign
    {
        public long AdCampaignId { get; set; } // AdCampaignID (Primary key)
        public string AdCampaignType { get; set; } // AdCampaignType (length: 100)
        public string AdCampaignTemplate { get; set; } // AdCampaignTemplate
        public string AdGroupName { get; set; } // AdGroupName (length: 500)
        public System.DateTime? DateCreated { get; set; } // DateCreated

        public AdCampaign()
        {
            DateCreated = System.DateTime.Now;
        }
    }

}
// </auto-generated>
