// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Pocogeneratortest.Entities
{

    // AdTemplates
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public class AdTemplate
    {
        public int Id { get; set; } // Id (Primary key)
        public long DealerId { get; set; } // DealerId
        public int? AdNumber { get; set; } // AdNumber
        public string Template { get; set; } // Template
        public System.DateTime? DateCreated { get; set; } // DateCreated
        public long? AdCampaignId { get; set; } // AdCampaignId
    }

}
// </auto-generated>
