// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Pocogeneratortest.Entities
{

    // Auditing
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public class Auditing
    {
        public int Id { get; set; } // Id (Primary key)
        public int UserId { get; set; } // UserId (Primary key)
        public string TableName { get; set; } // TableName (Primary key) (length: 100)
        public string ColumnName { get; set; } // ColumnName (Primary key) (length: 50)
        public string OldValue { get; set; } // OldValue (Primary key) (length: 200)
        public string NewValue { get; set; } // NewValue (Primary key) (length: 200)
        public string Action { get; set; } // Action (Primary key) (length: 50)
        public int IdentityValue { get; set; } // IdentityValue (Primary key)
        public System.DateTime Date { get; set; } // Date (Primary key)
    }

}
// </auto-generated>
