// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Pocogeneratortest.Entities
{

    // ExceptionLog
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public class ExceptionLog
    {
        public long Id { get; set; } // Id (Primary key)
        public string Message { get; set; } // Message
        public string ExceptionType { get; set; } // ExceptionType (length: 1000)
        public string ExceptionSource { get; set; } // ExceptionSource
        public string Url { get; set; } // URL
        public System.DateTime? Date { get; set; } // Date
        public string Comments { get; set; } // Comments
    }

}
// </auto-generated>
