// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Pocogeneratortest.Entities
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public class GetAdTemplatesReturnModel
    {
        public System.Int32? RowNumber { get; set; }
        public System.Int32? Id { get; set; }
        public System.Int32? DealerId { get; set; }
        public System.Int32? AdNumber { get; set; }
        public System.String Template { get; set; }
        public System.DateTime? DateCreated { get; set; }
        public System.Int32? AdCampaignId { get; set; }
    }

}
// </auto-generated>
