// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Pocogeneratortest.Entities
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public class GetExportLogsReturnModel
    {
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
        public class ResultSetModel1
        {
            public System.Int32? RowNumber { get; set; }
            public System.Int32? Id { get; set; }
            public System.String Url { get; set; }
            public System.DateTime? StartTime { get; set; }
            public System.DateTime? EndTime { get; set; }
            public System.String TotalTime { get; set; }
            public System.DateTime? Date { get; set; }
            public System.String Status { get; set; }
            public System.String Message { get; set; }
            public System.String FilePath { get; set; }
            public System.String FeedType { get; set; }
        }
        public System.Collections.Generic.List<ResultSetModel1> ResultSet1;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
        public class ResultSetModel2
        {
            public System.Int32? TotalRecords { get; set; }
        }
        public System.Collections.Generic.List<ResultSetModel2> ResultSet2;

    }

}
// </auto-generated>
