// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Pocogeneratortest.Entities
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public class GetVehicleOptionsReturnModel
    {
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
        public class ResultSetModel1
        {
            public System.Int32? Year { get; set; }
            public System.Int32? Selected { get; set; }
        }
        public System.Collections.Generic.List<ResultSetModel1> ResultSet1;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
        public class ResultSetModel2
        {
            public System.String Make { get; set; }
            public System.Int32? Selected { get; set; }
        }
        public System.Collections.Generic.List<ResultSetModel2> ResultSet2;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
        public class ResultSetModel3
        {
            public System.String Make { get; set; }
            public System.Int32? Selected { get; set; }
        }
        public System.Collections.Generic.List<ResultSetModel3> ResultSet3;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
        public class ResultSetModel4
        {
            public System.String Make { get; set; }
            public System.Int32? Selected { get; set; }
        }
        public System.Collections.Generic.List<ResultSetModel4> ResultSet4;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
        public class ResultSetModel5
        {
            public System.String Model { get; set; }
            public System.Int32? Selected { get; set; }
        }
        public System.Collections.Generic.List<ResultSetModel5> ResultSet5;

    }

}
// </auto-generated>
