// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Pocogeneratortest.Mapping
{
    using Pocogeneratortest.Entities;

    // AdCampaignSettings
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public class AdCampaignSettingConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<AdCampaignSetting>
    {
        public AdCampaignSettingConfiguration()
            : this("dbo")
        {
        }

        public AdCampaignSettingConfiguration(string schema)
        {
            ToTable("AdCampaignSettings", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.AdCampaignId).HasColumnName(@"AdCampaignId").HasColumnType("int").IsRequired();
            Property(x => x.DealerId).HasColumnName(@"DealerId").HasColumnType("int").IsOptional();
            Property(x => x.Platform).HasColumnName(@"Platform").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.Type).HasColumnName(@"Type").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(50);
            Property(x => x.CreateDate).HasColumnName(@"CreateDate").HasColumnType("datetime").IsRequired();
            Property(x => x.ModifiedDate).HasColumnName(@"ModifiedDate").HasColumnType("datetime").IsOptional();
        }
    }

}
// </auto-generated>
